### ISSUE TITLE
IPython Notebook (.ipynb) specific JSON?

### ISSUE THREAD

**Issue by mankoff** [jlumpe/ox-json#1]
Are there plans to support the JSON format that is .ipynb format?

**Comment by jlumpe** [comment]
That's sort of outside the scope of what this package is supposed to be, but the idea is once you have the data in JSON you can process it with any tools you want outside Emacs. The [pyorg](http://github.com/jlumpe/pyorg) package was written to work with this data in Python, I'm sure combining it with something like [nbformat](https://nbformat.readthedocs.io/en/latest/api.html#module-nbformat.v4) would get you what you need.
